name: C++ build

on: 
  push:
    branches:
      - dev

jobs:
  build_branch:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: branch name
      run: echo running on branch ${GITHUB_REF##*/}
    - name: build app
      run: make
