name: C++ Test

on: 
  schedule:
    - cron:  '20 2 * * *'
  push:
    branches:
      - test

jobs:
  test_app:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: branch name
      run: echo running on branch ${GITHUB_REF##*/}
    - name: test library
      run: make test
    - name: rebase master
      run: git rebase master test